config/routes.rb
Rails.application.routes.draw do
  resources :rationumbers

  root 'welcome#index'
end

app/models/rationumber.rb
class Rationumber < ActiveRecord::Base


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rationumbers_controller.rb
class RationumbersController < ApplicationController
#index, show, new, edit, create, update and destroy

#-----------------------------------------------------

  def show
   @dsc = Rationumber.find(params[:id])
  end

#----------------------------------------------------- 
  def new
  end
  
#-----------------------------------------------------
  def create
  @dsc = Rationumber.new(article_params)
 
  @dsc.save
  redirect_to @dsc
   end
 
  private
  def article_params
    params.require(:dsc).permit(:name, :profit, :debt)
  end
#-----------------------------------------------------  
  
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rationumbers_helper.rb
module RationumbersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dsc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rationumbers/new.html.erb
<h1>New Calculation</h1>


<%= form_for :dsc, url: rationumbers_path do |f| %>
<p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :profit %><br>
    <%= f.number_field :profit %>
  </p>
  <p>
    <%= f.label :debt %><br>
    <%= f.number_field :debt %>
  </p>
  <p>
    <%= submit_tag("Calculate") %>
  </p>
<% end %>

app/views/rationumbers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @dsc.name %>
</p>
 
<p>
  <strong>Profit:</strong>
  <%= @dsc.profit %>
</p>

<p>
  <strong>Debt:</strong>
  <%= @dsc.debt %>
</p>

app/views/welcome/index.html.erb
<h1>Debt Service Coverage Ratio</h1>
<p>This application will take in your profit and debt and calculate if you may qualify for a loan.</p>